spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth
            uri: lb://auth-service
            predicates:
              - Path=/auth/**
          - id: admin
            uri: lb://admin-service
            predicates:
              - Path=/admin/**
          - id: customer
            uri: lb://customer-service
            predicates:
              - Path=/customers/**
          - id: account
            uri: lb://account-service
            predicates:
              - Path=/accounts/**
          - id: credit
            uri: lb://credit-service
            predicates:
              - Path=/credits/**
          - id: payment
            uri: lb://payment-service
            predicates:
              - Path=/payments/**
          - id: notification
            uri: lb://notification-service
            predicates:
              - Path=/notifications/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

